"""Limited vector dimension to 256

Revision ID: 08f43fdc0b7d
Revises: d3238c5a0169
Create Date: 2024-09-05 17:23:25.973700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f43fdc0b7d'
down_revision: Union[str, None] = 'd3238c5a0169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
